class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror'
        self.UnzipMirrorCommand = 'unzip'
        self.TarMirrorCommand = 'tar'
        self.ZipMirrorCommand = 'zip'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'search'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch'
        self.TarWatchCommand = 'tarwatch'
        self.ZipWatchCommand = 'zipwatch'
        self.QbMirrorCommand = 'qbmirror'
        self.QbUnzipMirrorCommand = 'qbunzip'
        self.QbTarMirrorCommand = 'qbtar'
        self.QbZipMirrorCommand = 'qbzip'
        self.DeleteCommand = 'del'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'
        self.TsHelp1Command = 'tshelp1'

BotCommands = _BotCommands()
